### ISSUE TITLE
local install now doesn't work: Incompatible component merge errors

### ISSUE THREAD

**Issue by kkiesling** [conda-forge/dagmc-feedstock#15]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Although the latest PR that added MPI successfully passed CI, when trying to install locally in a clean environment, this error is now occurring:

```
>> conda create -n test_dagmc -c conda-forge dagmc
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 259, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 291, in get_reduced_index
        push_record(record)
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 265, in push_record
        combined_depends = record.combined_depends
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/models/records.py", line 340, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 480, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 480, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 511, in _merge
        final = this_component.merge(that_component)
      File "/home/kkiesling/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 763, in merge
        raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
    ValueError: Incompatible component merge:
      - 'mpi_openmpi_*'
      - 'mpi_openmpi_tempest*'
```

Discovered first by @paulromano - the best we can guess is that this is stemming from the MOAB exports [here](https://github.com/conda-forge/moab-feedstock/blob/main/recipe/meta.yaml#L44-L45)

I have posed a question to the conda forge gitter and will update here if I learn anything new.

### Installed packages

```shell
>> conda list
# packages in environment at /home/kkiesling/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
brotlipy                  0.7.0           py39h27cfd23_1003  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py39h06a4308_2  
cffi                      1.15.0           py39hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     4.11.0           py39h06a4308_0  
conda-content-trust       0.1.1              pyhd3eb1b0_0  
conda-package-handling    1.7.3            py39h27cfd23_1  
cryptography              36.0.0           py39h9ce1e76_0  
idna                      3.3                pyhd3eb1b0_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
ncurses                   6.3                  h7f8727e_2  
openssl                   1.1.1m               h7f8727e_0  
pip                       21.2.4           py39h06a4308_0  
pycosat                   0.6.3            py39h27cfd23_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.7                h12debd9_1  
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd3eb1b0_0  
ruamel_yaml               0.15.100         py39h27cfd23_0  
setuptools                58.0.4           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.37.0               hc218d9a_0  
tk                        8.6.11               h1ccaba5_0  
tqdm                      4.62.3             pyhd3eb1b0_1  
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.7             pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7f8727e_4
```

### Environment info

```shell
>> conda info

     active environment : base
    active env location : /home/kkiesling/miniconda3
            shell level : 1
       user config file : /home/kkiesling/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/kkiesling/miniconda3  (writable)
      conda av data dir : /home/kkiesling/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/kkiesling/miniconda3/pkgs
                          /home/kkiesling/.conda/pkgs
       envs directories : /home/kkiesling/miniconda3/envs
                          /home/kkiesling/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.7 Linux/5.4.0-94-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1012:1016
             netrc file : None
           offline mode : False
```

**Comment by shimwell** [comment]
+1 for adding downstream tests to DAGMC conda package

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#downstream-tests

**Comment by kkiesling** [comment]
This should be fixed by [this MOAB PR](https://github.com/conda-forge/moab-feedstock/pull/61) when the updated packages propagate through the system

**Comment by kkiesling** [comment]
That MOAB fix does not appear to have fixed this unfortunately

**Comment by xylar** [comment]
Oddly, I just did:
```
mamba create -n test_dagmc -c conda-forge dagmc
```
(i.e. `mamba` and not `conda`) and it worked just fine.

**Comment by xylar** [comment]
It seems like the incorrect previous `run_exports` may actually be breaking conda somehow.  It's very late where I live but it might be worth investigating sometime later if we can patch the previous builds of `moab` to also have correct `run_exports`.  I'll try looking into that tomorrow.  Feel free to reopen https://github.com/conda-forge/moab-feedstock/issues/60.

**Comment by xylar** [comment]
Hmm, doesn't seem like you can patch `run_exports`: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/224

**Comment by kkiesling** [comment]
Update on this issue. Even with the latest changes to both [MOAB](https://github.com/conda-forge/moab-feedstock/pull/62) and DAGMC (#19), `conda install -c conda-forge dagmc` still does not work, but `mamba` does. Prior to these latest changes in MOAB and DAGMC, building locally was not successful and produced the same component merge error noted above. But now, with these fixes, building locally _does_ actually work, but `conda install` still fails. I am _really_ not sure at this point why that is.

Error from `conda install -c conda-forge dagmc`:
```
    ValueError: Incompatible component merge:
      - 'mpi_mpich_*'
      - 'mpi_mpich_tempest*'
```

**Comment by CJ-Wright-Citadel** [comment]
Does it make sense to mark some of the `moab` artifacts as broken?

xref: https://github.com/conda/conda/issues/11442

@conda-forge-admin please ping conda-forge/core

**Comment by kkiesling** [comment]
@CJ-Wright-Citadel - Possibly? It is not entirely clear to me that it is strictly MOAB anymore because the `run_exports` was fixed there.

**Comment by CJ-Wright-Citadel** [comment]
Right, I'm concerned that the packages with the bad `run_exports` are still in the `repodata.json`, so people could still potentially pull it down and run into issues.

**Comment by kkiesling** [comment]
I tested this yesterday by first installing the correct MOAB package in an empty environment, and then trying to install DAGMC on top of that. I did `conda create -n moab_debug3 -c conda-forge "moab=5.3.1=*_tempest*"` which I confirmed did find the latest, and correctly named MOAB package that we needed. That succeeded. But then doing `conda install -c conda-forge dagmc` on top of that still failed.

**Comment by CJ-Wright** [comment]
@conda-forge/core

**Comment by jaimergp** [comment]
I see this as a bug in conda, honestly. These two expressions `mpi_mpich_*` and `mpi_mpich_tempest*` should be compatible (latter is a more specific case of the former). That said, the error reporting here can also be improved to at least mention which packages are incompatible. Finally, we'd need to think about how to control these strings in the wild, because it can easily get out of hand.

IIRC, `run_exports` cannot be patched in repodata (😢) so we might need to mark those affected as broken?

**Comment by hmaarrfk** [comment]
> IIRC, run_exports cannot be patched in repodata (😢) so we might need to mark those affected as broken?

This is my understanding as well.

**Comment by kkiesling** [comment]
It's good to get some confirmation that this is a conda issue, not an us issue. I have had an [issue](https://github.com/conda/conda/issues/11442) open on the conda repo for quite some time now.

**Comment by matthewfeickert** [comment]
What was the original expected result in terms of installed packages? I'm unable to reproduce the issue with `dagmc` `v3.2.4` for multiple build variants:

```console
$ pixi init issue-15 && cd issue-15 && pixi add dagmc && pixi list
✔ Created /tmp/issue-15/pixi.toml
✔ Added dagmc >=3.2.4,<4
Name             Version       Build                                   Size  Kind   Source
_libgcc_mutex    0.1           conda_forge                         2.50 KiB  conda  https://conda.anaconda.org/conda-forge
_openmp_mutex    4.5           2_gnu                              23.07 KiB  conda  https://conda.anaconda.org/conda-forge
attr             2.5.2         h39aace5_0                         66.48 KiB  conda  https://conda.anaconda.org/conda-forge
blosc            1.21.6        he440d0b_1                         47.29 KiB  conda  https://conda.anaconda.org/conda-forge
bzip2            1.0.8         hda65f42_8                        254.24 KiB  conda  https://conda.anaconda.org/conda-forge
c-ares           1.34.6        hb03c661_0                        203.01 KiB  conda  https://conda.anaconda.org/conda-forge
ca-certificates  2026.1.4      hbd8a1cb_0                        143.08 KiB  conda  https://conda.anaconda.org/conda-forge
dagmc            3.2.4         nompi_nodoubledown_h3f024ac_103    10.16 MiB  conda  https://conda.anaconda.org/conda-forge
eigen            3.4.0         h171cf75_1                          1.12 MiB  conda  https://conda.anaconda.org/conda-forge
hdf4             4.2.15        h2a13503_7                        739.01 KiB  conda  https://conda.anaconda.org/conda-forge
hdf5             1.14.6        nompi_h19486de_106                  3.54 MiB  conda  https://conda.anaconda.org/conda-forge
icu              78.2          h33c6efd_0                         12.14 MiB  conda  https://conda.anaconda.org/conda-forge
keyutils         1.6.3         hb9d3cd8_0                        130.95 KiB  conda  https://conda.anaconda.org/conda-forge
krb5             1.21.3        h659f571_0                          1.31 MiB  conda  https://conda.anaconda.org/conda-forge
libaec           1.1.5         h088129d_0                         35.69 KiB  conda  https://conda.anaconda.org/conda-forge
libblas          3.11.0        5_h4a7cf45_openblas                17.79 KiB  conda  https://conda.anaconda.org/conda-forge
libcurl          8.18.0        h4e3cde8_0                        452.09 KiB  conda  https://conda.anaconda.org/conda-forge
libedit          3.1.20250104  pl5321h7949ede_0                  131.52 KiB  conda  https://conda.anaconda.org/conda-forge
libev            4.33          hd590300_2                        110.12 KiB  conda  https://conda.anaconda.org/conda-forge
libgcc           15.2.0        he0feb66_17                      1016.09 KiB  conda  https://conda.anaconda.org/conda-forge
libgcc-ng        15.2.0        h69a702a_17                        26.90 KiB  conda  https://conda.anaconda.org/conda-forge
libgfortran      15.2.0        h69a702a_17                        26.87 KiB  conda  https://conda.anaconda.org/conda-forge
libgfortran5     15.2.0        h68bc16d_17                         2.37 MiB  conda  https://conda.anaconda.org/conda-forge
libgomp          15.2.0        he0feb66_17                       589.19 KiB  conda  https://conda.anaconda.org/conda-forge
libiconv         1.18          h3b78370_2                        771.66 KiB  conda  https://conda.anaconda.org/conda-forge
libjpeg-turbo    3.1.2         hb03c661_0                        618.86 KiB  conda  https://conda.anaconda.org/conda-forge
liblapack        3.11.0        5_h47877c9_openblas                17.77 KiB  conda  https://conda.anaconda.org/conda-forge
liblzma          5.8.2         hb03c661_0                        110.55 KiB  conda  https://conda.anaconda.org/conda-forge
libnetcdf        4.9.3         nompi_hbf2fc22_104                850.38 KiB  conda  https://conda.anaconda.org/conda-forge
libnghttp2       1.67.0        had1ee68_0                        650.98 KiB  conda  https://conda.anaconda.org/conda-forge
libopenblas      0.3.30        pthreads_h94d23a6_4                 5.65 MiB  conda  https://conda.anaconda.org/conda-forge
libssh2          1.11.1        hcf80075_0                        297.65 KiB  conda  https://conda.anaconda.org/conda-forge
libstdcxx        15.2.0        h934c35e_17                         5.58 MiB  conda  https://conda.anaconda.org/conda-forge
libstdcxx-ng     15.2.0        hdf11a46_17                        26.93 KiB  conda  https://conda.anaconda.org/conda-forge
libxml2          2.15.1        he237659_1                         44.34 KiB  conda  https://conda.anaconda.org/conda-forge
libxml2-16       2.15.1        hca6bf5a_1                        542.72 KiB  conda  https://conda.anaconda.org/conda-forge
libzip           1.11.2        h6991a6a_0                        106.49 KiB  conda  https://conda.anaconda.org/conda-forge
libzlib          1.3.1         hb9d3cd8_2                         59.53 KiB  conda  https://conda.anaconda.org/conda-forge
lz4-c            1.10.0        h5888daf_1                        163.14 KiB  conda  https://conda.anaconda.org/conda-forge
metis            5.1.0         hd0bcaf9_1007                       3.74 MiB  conda  https://conda.anaconda.org/conda-forge
moab             5.6.0         nompi_tempest_h3811aa1_0            4.42 MiB  conda  https://conda.anaconda.org/conda-forge
ncurses          6.5           h2d0b736_3                        870.74 KiB  conda  https://conda.anaconda.org/conda-forge
openssl          3.6.1         h35e630c_1                          3.02 MiB  conda  https://conda.anaconda.org/conda-forge
snappy           1.2.2         h03e3b7b_1                         44.75 KiB  conda  https://conda.anaconda.org/conda-forge
tempest-remap    2.2.0         h397758c_8                        994.43 KiB  conda  https://conda.anaconda.org/conda-forge
zlib             1.3.1         hb9d3cd8_2                         90.12 KiB  conda  https://conda.anaconda.org/conda-forge
zstd             1.5.7         hb78ec9c_6                        587.28 KiB  conda  https://conda.anaconda.org/conda-forge
```

```console
$ pixi init issue-15 && cd issue-15 && pixi add 'dagmc [build=mpi_mpich_doubledown_*]' && pixi list
✔ Created /tmp/issue-15/pixi.toml
✔ Added dagmc [build=mpi_mpich_doubledown_*]
Name             Version       Build                                   Size  Kind   Source
_libgcc_mutex    0.1           conda_forge                         2.50 KiB  conda  https://conda.anaconda.org/conda-forge
_openmp_mutex    4.5           2_gnu                              23.07 KiB  conda  https://conda.anaconda.org/conda-forge
attr             2.5.2         h39aace5_0                         66.48 KiB  conda  https://conda.anaconda.org/conda-forge
blosc            1.21.6        he440d0b_1                         47.29 KiB  conda  https://conda.anaconda.org/conda-forge
bzip2            1.0.8         hda65f42_8                        254.24 KiB  conda  https://conda.anaconda.org/conda-forge
c-ares           1.34.6        hb03c661_0                        203.01 KiB  conda  https://conda.anaconda.org/conda-forge
ca-certificates  2026.1.4      hbd8a1cb_0                        143.08 KiB  conda  https://conda.anaconda.org/conda-forge
dagmc            3.2.4         mpi_mpich_doubledown_h6e858db_3    10.22 MiB  conda  https://conda.anaconda.org/conda-forge
eigen            3.4.0         h171cf75_1                          1.12 MiB  conda  https://conda.anaconda.org/conda-forge
embree           4.4.0         ha751380_1                          9.07 MiB  conda  https://conda.anaconda.org/conda-forge
hdf4             4.2.15        h2a13503_7                        739.01 KiB  conda  https://conda.anaconda.org/conda-forge
hdf5             1.14.6        mpi_mpich_hfe583f4_6                3.74 MiB  conda  https://conda.anaconda.org/conda-forge
icu              78.2          h33c6efd_0                         12.14 MiB  conda  https://conda.anaconda.org/conda-forge
keyutils         1.6.3         hb9d3cd8_0                        130.95 KiB  conda  https://conda.anaconda.org/conda-forge
krb5             1.21.3        h659f571_0                          1.31 MiB  conda  https://conda.anaconda.org/conda-forge
libaec           1.1.5         h088129d_0                         35.69 KiB  conda  https://conda.anaconda.org/conda-forge
libblas          3.11.0        5_h4a7cf45_openblas                17.79 KiB  conda  https://conda.anaconda.org/conda-forge
libcap           2.77          h3ff7636_0                        118.58 KiB  conda  https://conda.anaconda.org/conda-forge
libcurl          8.18.0        h4e3cde8_0                        452.09 KiB  conda  https://conda.anaconda.org/conda-forge
libedit          3.1.20250104  pl5321h7949ede_0                  131.52 KiB  conda  https://conda.anaconda.org/conda-forge
libev            4.33          hd590300_2                        110.12 KiB  conda  https://conda.anaconda.org/conda-forge
libfabric        2.4.0         ha770c72_1                         14.07 KiB  conda  https://conda.anaconda.org/conda-forge
libfabric1       2.4.0         h8f87c3e_1                        683.45 KiB  conda  https://conda.anaconda.org/conda-forge
libgcc           15.2.0        he0feb66_17                      1016.09 KiB  conda  https://conda.anaconda.org/conda-forge
libgcc-ng        15.2.0        h69a702a_17                        26.90 KiB  conda  https://conda.anaconda.org/conda-forge
libgfortran      15.2.0        h69a702a_17                        26.87 KiB  conda  https://conda.anaconda.org/conda-forge
libgfortran-ng   15.2.0        h69a702a_17                        26.91 KiB  conda  https://conda.anaconda.org/conda-forge
libgfortran5     15.2.0        h68bc16d_17                         2.37 MiB  conda  https://conda.anaconda.org/conda-forge
libgomp          15.2.0        he0feb66_17                       589.19 KiB  conda  https://conda.anaconda.org/conda-forge
libhwloc         2.12.2        default_hafda6a7_1000               2.34 MiB  conda  https://conda.anaconda.org/conda-forge
libiconv         1.18          h3b78370_2                        771.66 KiB  conda  https://conda.anaconda.org/conda-forge
libjpeg-turbo    3.1.2         hb03c661_0                        618.86 KiB  conda  https://conda.anaconda.org/conda-forge
liblapack        3.11.0        5_h47877c9_openblas                17.77 KiB  conda  https://conda.anaconda.org/conda-forge
liblzma          5.8.2         hb03c661_0                        110.55 KiB  conda  https://conda.anaconda.org/conda-forge
libnetcdf        4.9.3         mpi_mpich_he3cb82c_4              860.37 KiB  conda  https://conda.anaconda.org/conda-forge
libnghttp2       1.67.0        had1ee68_0                        650.98 KiB  conda  https://conda.anaconda.org/conda-forge
libnl            3.11.0        hb9d3cd8_0                        723.95 KiB  conda  https://conda.anaconda.org/conda-forge
libopenblas      0.3.30        pthreads_h94d23a6_4                 5.65 MiB  conda  https://conda.anaconda.org/conda-forge
libpnetcdf       1.14.1        mpi_mpich_h3dbf9f6_100              2.40 MiB  conda  https://conda.anaconda.org/conda-forge
libssh2          1.11.1        hcf80075_0                        297.65 KiB  conda  https://conda.anaconda.org/conda-forge
libstdcxx        15.2.0        h934c35e_17                         5.58 MiB  conda  https://conda.anaconda.org/conda-forge
libstdcxx-ng     15.2.0        hdf11a46_17                        26.93 KiB  conda  https://conda.anaconda.org/conda-forge
libsystemd0      257.10        hd0affe5_4                        480.42 KiB  conda  https://conda.anaconda.org/conda-forge
libudev1         257.10        hd0affe5_4                        141.26 KiB  conda  https://conda.anaconda.org/conda-forge
libxcrypt        4.4.36        hd590300_1                         98.04 KiB  conda  https://conda.anaconda.org/conda-forge
libxml2          2.15.1        he237659_1                         44.34 KiB  conda  https://conda.anaconda.org/conda-forge
libxml2-16       2.15.1        hca6bf5a_1                        542.72 KiB  conda  https://conda.anaconda.org/conda-forge
libzip           1.11.2        h6991a6a_0                        106.49 KiB  conda  https://conda.anaconda.org/conda-forge
libzlib          1.3.1         hb9d3cd8_2                         59.53 KiB  conda  https://conda.anaconda.org/conda-forge
lz4-c            1.10.0        h5888daf_1                        163.14 KiB  conda  https://conda.anaconda.org/conda-forge
metis            5.1.0         hd0bcaf9_1007                       3.74 MiB  conda  https://conda.anaconda.org/conda-forge
moab             5.6.0         mpi_mpich_tempest_h1d40c9e_0        6.03 MiB  conda  https://conda.anaconda.org/conda-forge
mpi              1.0.1         mpich                               6.37 KiB  conda  https://conda.anaconda.org/conda-forge
mpich            4.3.2         h23078de_105                        5.75 MiB  conda  https://conda.anaconda.org/conda-forge
ncurses          6.5           h2d0b736_3                        870.74 KiB  conda  https://conda.anaconda.org/conda-forge
openssl          3.6.1         h35e630c_1                          3.02 MiB  conda  https://conda.anaconda.org/conda-forge
perl             5.32.1        7_hd590300_perl5                   12.73 MiB  conda  https://conda.anaconda.org/conda-forge
rdma-core        61.0          h192683f_0                          1.21 MiB  conda  https://conda.anaconda.org/conda-forge
snappy           1.2.2         h03e3b7b_1                         44.75 KiB  conda  https://conda.anaconda.org/conda-forge
tbb              2022.3.0      hb700be7_2                        177.08 KiB  conda  https://conda.anaconda.org/conda-forge
tempest-remap    2.2.0         h397758c_8                        994.43 KiB  conda  https://conda.anaconda.org/conda-forge
ucx              1.20.0        hf72d326_1                          7.44 MiB  conda  https://conda.anaconda.org/conda-forge
zlib             1.3.1         hb9d3cd8_2                         90.12 KiB  conda  https://conda.anaconda.org/conda-forge
zoltan           3.901         mpi_mpich_hbcf76dd_2              500.88 KiB  conda  https://conda.anaconda.org/conda-forge
zstd             1.5.7         hb78ec9c_6                        587.28 KiB  conda  https://conda.anaconda.org/conda-forge
```

If this can't be reproduced anymore should it be closed?

**Comment by hmaarrfk** [comment]
IMO yes
